// flow-typed signature: b041d75cad355bfd99e734db00bc1a28
// flow-typed version: <<STUB>>/clear-console_v1.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clear-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clear-console' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'clear-console/index' {
  declare module.exports: $Exports<'clear-console'>;
}
declare module 'clear-console/index.js' {
  declare module.exports: $Exports<'clear-console'>;
}
